apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'http://cluster-gke-cluster:8001'
    namespace: ambient
  source:
    path: application
    repoURL: 'https://github.com/therealmitchconnors/argo-reference-ambient'
    targetRevision: HEAD
    directory:
      exclude: application.yaml
  project: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true