apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Meta Application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
    server: ''
  source:
    path: istio-control-1.19
    repoURL: 'https://github.com/therealmitchconnors/argo-reference-ambient'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2