apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applink-multicluster
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # - clusters: {}
  - clusters: 
      values:
        defaultChannel: '{{index .metadata.labels "defaultChannel" }}'
      selector:
        matchExpressions:
        - { key: defaultChannel, operator: Exists }
  template:
    metadata:
      name: applink-{{.name}}
    spec:
      project: msft-mesh-admin
      sources:
      - path: applink-meta
        repoURL: 'https://github.com/therealmitchconnors/argo-reference-ambient'
        targetRevision: multicluster
        helm:
          valuesObject:
            revisions:
            - name: "1-23-3"
              version: "1.23.3"
            - name: "1-23-2"
              version: "1.23.2"
              tags:
              - legacy
              - stable
            - name: "1-24-1"
              version: "1.24.1"
              tags:
              - rapid
            defaultTag: '{{ .metadata.labels.defaultChannel }}'
            clusterName: '{{.name}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
