apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control-1.19
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'http://cluster-gke-cluster:8001'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.19.3
      helm:
        valuesObject:
          revision: 1-19-3
        valueFiles:
          - >-
            $values/manifests/charts/istio-control/istio-discovery/ambient-values.yaml
      chart: istiod
    - repoURL: 'https://github.com/istio/istio.git'
      targetRevision: 1.19.3
      ref: values
