apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-tags
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'http://cluster-gke-cluster:8001'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - path: tag-chart
      repoURL: 'https://github.com/therealmitchconnors/argo-reference-ambient'
      targetRevision: HEAD
      helm:
        valueObjects:
          base:
            tags:
              default:
                revision: "1-18-3"
              stable:
                revision: "1-18-3"
              rapid:
                revision: "1-19-3"