apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-tags
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: msft-mesh-admin
  destination:
    name: ambient-cluster
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: tag-chart
    repoURL: 'https://github.com/therealmitchconnors/argo-reference-ambient'
    targetRevision: HEAD
    helm:
      valuesObject:
        base:
          tags:
            default:
              revision: "1-23-3"
            stable:
              revision: "1-22-5"
            rapid:
              revision: "1-24-1"
          ztshim: "1-24-1"