apiVersion: v1
kind: Service
metadata:
  name: loadgen
  labels:
    app: loadgen
    service: loadgen
spec:
  ports:
  - port: 8089
    name: http
  selector:
    app: loadgen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: therealmitchconnors/bookinfo-load-test:latest
        imagePullPolicy: Always
        args: ["-h","http://bookinfo-gateway-istio","-u","50","-r","1"]
        ports:
        - containerPort: 9080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reset-locust-stats
spec:
  schedule: "35 0/6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resetter
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "wget loadgen:8089/stats/reset"
          restartPolicy: OnFailure